### ISSUE TITLE
TypeError: must be str, not bytes when using fill_form

### ISSUE THREAD

**Issue by rhaejr** [revolunet/pypdftk#12]
```
Traceback (most recent call last):
  File "C:/Users/Rhea/Documents/GitHub/LeaveFormFiller/leaveForm.py", line 395, in submit_leave
    self.leave_form.create_form()
  File "C:/Users/Rhea/Documents/GitHub/LeaveFormFiller/leaveForm.py", line 161, in create_form
    fill_form("leaveForm.pdf", self.datas )
  File "C:\Python34\lib\site-packages\pypdftk.py", line 55, in fill_form
    tmp_fdf = gen_xfdf(datas)
  File "C:\Python34\lib\site-packages\pypdftk.py", line 129, in gen_xfdf
    f.write(tpl.encode('UTF-8'))
TypeError: must be str, not bytes
```

Best I can tell, everything I am sending to fill_form is a 'str'. I went through the debugger just to make sure, there isn't anything that isn't a str on my end. It still may be my fault. I was using fdfgen and it uses a list instead of a dict. So i had to change all of that.

Edit: This using python 3.4 not sure if that is the issue or not.

**Comment by iurisilvio** [comment]
I think this project wasn't tested with py3.

It is a good time to provide some support.

**Comment by revolunet** [comment]
should be fixed soon : https://github.com/revolunet/pypdftk/pull/23

**Comment by dexzmen** [comment]
try installing it from github:
`pip install git+https://github.com/revolunet/pypdftk.git`
