### ISSUE TITLE
Concat function doesn't work

### ISSUE THREAD

**Issue by lcsavb** [revolunet/pypdftk#30]
Hi! The concat function is breaking the input archive filename into single letters. I was unable to fix it.

Thanks.

`python3 fillpdf.py 
]Error: Unable to find file.
Error: Failed to open PDF file: 
   ,
Error: Unable to find file.
Error: Failed to open PDF file: 
   a
Error: Unable to find file.
Error: Failed to open PDF file: 
   r
Error: Unable to find file.
Error: Failed to open PDF file: 
   o
Error: Unable to find file.
Error: Failed to open PDF file: 
   t
Error: Unable to find file.
Error: Failed to open PDF file: 
   o
Errors encountered.  No output created.
Done.  Input errors, so no output created.
Traceback (most recent call last):
  File "fillpdf.py", line 10, in <module>
    out_pdf = pypdftk.concat('c,garoto', 'mesclado.pdf')
  File "/home/lucas/.local/lib/python3.7/site-packages/pypdftk.py", line 116, in concat
    run_command(args)
  File "/home/lucas/.local/lib/python3.7/site-packages/pypdftk.py", line 43, in run_command
    p = check_output(command, shell=shell)
  File "/home/lucas/.local/lib/python3.7/site-packages/pypdftk.py", line 37, in check_output
    raise subprocess.CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/pdftk', 'c', ',', 'g', 'a', 'r', 'o', 't', 'o', 'cat', 'output', 'mesclado.pdf']' returned non-zero exit status 1.`

**Comment by lcsavb** [comment]
I've found my mistake.....
sorry
